### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 查询所有用户
GET http://localhost:8080/users

### 根据ID查询用户
GET http://localhost:8080/users/1

### 新增用户
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "Jan",
  "password": "123456",
  "age": 27,
  "email": "Jan@example.com"
}
### 修改用户
PUT http://localhost:8080/users/1
Content-Type: application/json

{
"username": "Mark",
"password": "123456",
"age": 30,
"email": "Mark@example.com"
}

### 删除用户
DELETE http://localhost:8080/users/1

### 测试异常：查询不存在用户
GET http://localhost:8080/users/99999
